---
- hosts: all
  gather_facts: true
  become: true

  pre_tasks:
    - name: Make sure ansible works.
      ping:
       data: "woohoo!"

    - name: Configure new user with sudo access.
      block:
        - name: Make sure we have a 'wheel' group
          group:
            name: wheel
            state: present

        - name: Allow 'wheel' group to have passwordless sudo
          lineinfile:
            dest: /etc/sudoers
            state: present
            regexp: '^%wheel'
            line: '%wheel ALL=(ALL) NOPASSWD: ALL'
            validate: visudo -cf %s

        - name: Add sudoers users to wheel group
          user:
            name: "retro"
            groups: wheel
            append: yes
            password: "$6$X0WdoMeAwa$hP05bWIV/784IZuNkc4KaorWlrI.f8Vg0NuZ/CKph0qhAc5HiKsnS.BUNb5ooHDUND7F0eO.KC/1AHFpC5FsM."

  tasks:
    - name: Configure packages and restart vm.
      block:
        - name: Update & upgrade.
          apt:
           update_cache: "yes"
           cache_valid_time: 3600
           upgrade: "yes"

        - name: Install a list of packages
          apt:
           name:
           - 'dialog'
           - 'git'
           - 'unzip'
           - 'usbutils'
           - 'xfce4'
           - 'xfce4-terminal'
           - 'xmlstarlet'
           - 'libasound2'
           - 'alsa-base'
           - 'alsa-utils'
           - 'alsa-oss'
           state: present

        - name: restart vm
          reboot:

    - name: Download and configure, but not run setup, for retropie.
      block:
        - name: Creates directory
          file:
            path: "/home/retro/git/RetroPie-Setup"
            state: directory
            recurse: yes

        - name: Clone retropi repo.
          git:
            clone: "yes"
            depth: "1"
            dest: "/home/retro/git/RetroPie-Setup"
            repo: "https://github.com/RetroPie/RetroPie-Setup.git"
            version: "f2884e425a13535d1899c617acbe6a3c440e6f84"

        - name: Set setup script as executable.
          file:
            path: "/home/retro/git/RetroPie-Setup/retropie_setup.sh"
            mode: '777'
